import React from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { 
  Briefcase, 
  FileSearch, 
  FileText, 
  Map, 
  CheckCircle2, 
  ArrowRight, 
  Terminal,
  ShieldCheck
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';

// Feature data matches your Dashboard structure
const features = [
  {
    icon: Briefcase,
    title: "Curated Job Board",
    description: "Verified opportunities posted daily. No spam, just real placements for your batch.",
    color: "text-blue-500"
  },
  {
    icon: FileSearch,
    title: "ATS Resume Scanner",
    description: "Beat the bots. Get instant AI feedback on your resume's parseability.",
    color: "text-green-500"
  },
  {
    icon: FileText,
    title: "Resume Builder",
    description: "Create professional, LaTeX-style resumes that stand out to recruiters.",
    color: "text-orange-500"
  },
  {
    icon: Map,
    title: "Career Roadmaps",
    description: "Step-by-step learning paths generated by AI to guide your tech journey.",
    color: "text-purple-500"
  }
];

const steps = [
  { 
    id: 1, 
    title: "Create Account", 
    desc: "Sign up with your student email to access the portal." 
  },
  { 
    id: 2, 
    title: "Complete Profile", 
    desc: "Upload your resume and set your preferences (Internship/Full-time)." 
  },
  { 
    id: 3, 
    title: "Start Applying", 
    desc: "Apply to verified listings and track your status in real-time." 
  }
];

export default function Home() {
  const navigate = useNavigate();

  // Temporary mock login handler
  const handleLoginClick = () => {
    // In the real backend, this will check auth
    // For now, we redirect to show the flow
    navigate('/dashboard'); 
  };

  return (
    <div className="min-h-screen bg-background text-foreground selection:bg-primary/20">
      
      {/* --- NAVBAR --- */}
      <nav className="fixed top-0 w-full z-50 bg-background/80 backdrop-blur-md border-b border-border/40">
        <div className="container mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2 font-bold text-xl tracking-tight">
            <div className="p-1.5 bg-primary rounded-lg">
              <Terminal className="w-5 h-5 text-primary-foreground" />
            </div>
            CareerForge
          </div>
          <div className="flex items-center gap-4">
            <Button variant="ghost" className="hidden sm:flex">How it works</Button>
            <Button onClick={handleLoginClick}>Login</Button>
          </div>
        </div>
      </nav>

      {/* --- HERO SECTION --- */}
      <section className="pt-32 pb-20 px-6">
        <div className="container mx-auto text-center max-w-4xl">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
          >
            <span className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 text-primary text-sm font-medium mb-6">
              <ShieldCheck className="w-4 h-4" /> Verified Opportunities Only
            </span>
            <h1 className="text-4xl md:text-6xl font-bold tracking-tight mb-6 bg-gradient-to-r from-foreground to-foreground/60 bg-clip-text text-transparent">
              Your One-Stop Destination for <br className="hidden md:block" />
              <span className="text-primary">Tech Placements</span>
            </h1>
            <p className="text-lg md:text-xl text-muted-foreground mb-8 max-w-2xl mx-auto">
              Stop scrolling through endless spam. Access verified job listings, build ATS-friendly resumes, and follow AI-generated roadmaps to land your dream role.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <Button size="lg" className="h-12 px-8 text-base" onClick={handleLoginClick}>
                Get Started
                <ArrowRight className="ml-2 w-4 h-4" />
              </Button>
              <Button size="lg" variant="outline" className="h-12 px-8 text-base">
                View Demo
              </Button>
            </div>
          </motion.div>
        </div>
      </section>

      {/* --- FEATURES GRID --- */}
      <section className="py-20 bg-muted/30">
        <div className="container mx-auto px-6">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold mb-4">Everything you need to get hired</h2>
            <p className="text-muted-foreground">Comprehensive tools to accelerate your career.</p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {features.map((feature, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
              >
                <Card className="h-full hover:shadow-lg transition-all border-border/50">
                  <CardContent className="p-6">
                    <div className={`w-12 h-12 rounded-xl bg-background flex items-center justify-center mb-4 shadow-sm ${feature.color}`}>
                      <feature.icon className="w-6 h-6" />
                    </div>
                    <h3 className="text-xl font-semibold mb-2">{feature.title}</h3>
                    <p className="text-muted-foreground text-sm leading-relaxed">
                      {feature.description}
                    </p>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* --- HOW IT WORKS (The Guide) --- */}
      <section className="py-20 px-6">
        <div className="container mx-auto max-w-5xl">
          <div className="flex flex-col md:flex-row gap-12 items-center">
            <div className="flex-1 space-y-8">
              <h2 className="text-3xl font-bold">Your path to placement</h2>
              <div className="space-y-6">
                {steps.map((step) => (
                  <div key={step.id} className="flex gap-4">
                    <div className="flex-shrink-0 w-8 h-8 rounded-full bg-primary text-primary-foreground flex items-center justify-center font-bold">
                      {step.id}
                    </div>
                    <div>
                      <h3 className="font-semibold text-lg">{step.title}</h3>
                      <p className="text-muted-foreground">{step.desc}</p>
                    </div>
                  </div>
                ))}
              </div>
              <Button onClick={handleLoginClick} size="lg" className="mt-4">
                Launch Dashboard
              </Button>
            </div>
            
            {/* Visual Decoration for Steps */}
            <div className="flex-1 relative">
              <div className="absolute inset-0 bg-primary/20 blur-3xl rounded-full opacity-20" />
              <div className="relative bg-card border rounded-2xl p-6 shadow-2xl rotate-3 hover:rotate-0 transition-transform duration-500">
                <div className="flex items-center gap-4 mb-4 border-b pb-4">
                  <div className="w-10 h-10 rounded-full bg-muted animate-pulse" />
                  <div className="space-y-2">
                    <div className="h-4 w-32 bg-muted rounded animate-pulse" />
                    <div className="h-3 w-20 bg-muted rounded animate-pulse" />
                  </div>
                </div>
                <div className="space-y-3">
                  <div className="h-20 bg-muted/50 rounded-lg animate-pulse" />
                  <div className="h-20 bg-muted/50 rounded-lg animate-pulse" />
                </div>
                <div className="mt-4 flex justify-end">
                   <div className="h-8 w-24 bg-primary/20 rounded animate-pulse" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* --- FOOTER --- */}
      <footer className="py-8 border-t border-border/40 text-center text-muted-foreground text-sm">
        <p>© 2025 CareerForge. Verified Opportunities by Admin.</p>
      </footer>
    </div>
  );
}